# Generated by Django 5.0.3 on 2024-04-02 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('partido', models.CharField(choices=[('Partido1', 'Partido 1'), ('Partido2', 'Partido 2'), ('Partido3', 'Partido 3'), ('Partido4', 'Partido 4')], max_length=100)),
            ],
        ),
    ]
