# Usa la imagen base de MySQL
FROM mysql:8.3.0

# Variables de entorno para configurar la base de datos
ENV MYSQL_ROOT_PASSWORD=root1234
ENV MYSQL_DATABASE=elecciones

# Opcional: expone el puerto de MySQL
EXPOSE 3306